spring:
  application:
    name: main-svc

  datasource:
    url: "jdbc:postgresql://${MAIN_HOST}:${MAIN_DB_PORT}/${MAIN_DB}" # host = localhost, db = main
    username: "${MAIN_USER}" # user = main_user
    password: "${MAIN_PASSWORD}" # password = main_password
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true

  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: validate

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


springdoc:
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: method
    path: /main-svc/swagger-ui.html
    url: http://localhost:${GATEWAY_PORT}
  api-docs:
    path: /main-svc/v3/api-docs
