spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 86400000

http:
  headers:
    user-id: UserId