spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    secret-key: "${JWT_SECRET_KEY}"
    expiration-time: 86400000
  api-key: "${API_KEY}"

http:
  headers:
    user-id: UserId

server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: "${SSL_KEYSTORE_PASSWORD}"
    key-store-type: PKCS12
    key-alias: chily-ssl-key
  port: ${GATEWAY_PORT}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /main-svc/v3/api-docs
        name: Main Service
      - url: /security-svc/v3/api-docs
        name: Security Service
      - url: /places-svc/v3/api-docs
        name: Places Service
      - url: /feedback-svc/v3/api-docs
        name: Feedback Service
      - url: /business-users-svc/v3/api-docs
        name: Business Users Service
      - url: /files-svc/v3/api-docs
        name: Files Service
  api-docs:
    enabled: true
