spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: main-svc
          uri: lb://main-svc
          predicates:
            - Path=/api/user

        - id: security-svc
          uri: lb://security-svc
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
