spring:
  application:
    name: security-svc

  datasource:
    url: "jdbc:postgresql://${SEC_HOST}:5433/${SEC_DB}" # host = localhost, db = security
    username: "${SEC_USER}" # user = sec_user
    password: "${SEC_PASSWORD}" # password = sec_password
    driver-class-name: org.postgresql.Driver


  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform:

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 86400000
  refresh-token:
    expiration-time: 2592000000

http:
  headers:
    user-id: UserId

springdoc:
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: method
    path: /security-svc/swagger-ui.html
    url: http://localhost:8080
  api-docs:
    path: /security-svc/v3/api-docs
