spring:
  application:
    name: security-svc

  datasource:
    url: "jdbc:postgresql://${SEC_HOST}:${SEC_DB_PORT}/${SEC_DB}" # host = localhost, db = security
    username: "${SEC_USER}" # user = sec_user
    password: "${SEC_PASSWORD}" # password = sec_password
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true

  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: validate

  mail:
    host: smtp.gmail.com
    port: 587
    username: "${EMAIL_USERNAME}"
    password: "${EMAIL_PASSWORD}"

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret-key: "${JWT_SECRET_KEY}"
    expiration-time: 86400000
  refresh-token:
    expiration-time: 2592000000

http:
  headers:
    user-id: UserId

springdoc:
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: method
    path: /security-svc/swagger-ui.html
    url: http://localhost:${GATEWAY_PORT}
  api-docs:
    path: /security-svc/v3/api-docs