spring:
  application:
    name: business-users-svc

  datasource:
    url: "jdbc:postgresql://${BIZ_USR_HOST}:${BIZ_USR_DB_PORT}/${BIZ_USR_DB}" # host = localhost, db = feedback
    username: "${BIZ_USR_USER}" # user = feedback_user
    password: "${BIZ_USR_PASSWORD}" # password = feedback_password
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: method
    path: /business-users-svc/swagger-ui.html
    url: http://localhost:${GATEWAY_PORT}
  api-docs:
    path: /business-users-svc/v3/api-docs