name: backend ci-cd pipeline

on:
  pull_request:
    branches: ['main']

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up jdk 17
        uses: actions/setup-java@v4.2.2

        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn --batch-mode --update-snapshots test

  docker-image:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Compose Build & Push
        uses: 0x4r45h/docker-compose-ci@v0.1.1

  deploy:
    runs-on: ubuntu-latest
    needs: docker-image

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: amplium/git-crypt-action@v0.1.5
        with:
          key_encoded: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Send .env & docker-compose.yml file to the virtual machine
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: ".env, docker-compose.yml"
          target: /app/main/

      - name: Start backend service
        uses: garygrossgarten/github-action-ssh@0.8.0
        with:
          command: cd /app/main/ && docker compose down && docker compose pull && docker compose up -d
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}