name: backend ci-cd pipeline

on:
  pull_request:
    branches: ['main']

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Set up jdk 17
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn --batch-mode --update-snapshots test

      - name: Run surfire reporter
        run: mvn surefire-report:report

      - name: Upload JUnit HTML test reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-html-report
          path: '**/target/reports'

  docker-image:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: actions/checkout@v4.1.7
      - uses: amplium/git-crypt-action@v0.1.5
        with:
          key_encoded: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Docker Compose Build & Push
        uses: 0x4r45h/docker-compose-ci@v0.1.1