name: deploy backend on main server

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: amplium/git-crypt-action@v0.1.5
        with:
          key_encoded: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Send .env & docker-compose.yml file to the virtual machine
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: ".env, docker-compose.yml"
          target: /app/main/

      - name: Start backend service
        uses: garygrossgarten/github-action-ssh@0.8.0
        with:
          command: cd /app/main/ && docker compose down && docker compose pull && docker compose up -d
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
